name: Sonar minimal

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  PROJECT_KEY: Django

jobs:
  sonar:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Quick GET check
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        run: |
          BASE="${SONAR_HOST_URL%/}"
          echo "GET $BASE/api/system/status"
          curl -sf -u "$SONAR_TOKEN:" "$BASE/api/system/status" && echo

      - name: Minimal POST reachability (should return 400 fast)
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        run: |
          set -x
          BASE="${SONAR_HOST_URL%/}"
          echo x > dummy.zip
          # If POST path is reachable, SonarQube replies quickly with 400 Bad Request (invalid report).
          # If it TIMES OUT, something on the path is blocking/buffering multipart POSTs.
          curl --http1.1 -u "${SONAR_TOKEN}:" \
               -F "projectKey=${{ env.PROJECT_KEY }}" \
               -F "report=@dummy.zip" \
               -sS -o /dev/stderr -w "HTTP:%{http_code}\n" \
               "${BASE}/api/ce/submit"

      - name: Sonar scan (vanilla)
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: |
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.log.level=DEBUG
            -Dsonar.verbose=true
            -Dsonar.scanner.http.connectTimeout=60000
            -Dsonar.scanner.http.socketTimeout=600000
