name: Sonar minimal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_KEY: Django

jobs:
  sonar:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Quick sanity: is the server reachable?
      - name: Sonar status
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # e.g. https://sonarqube-rps908qj.lab.practical-devsecops.training
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        run: |
          set -e
          BASE="${SONAR_HOST_URL%/}"
          echo "GET $BASE/api/system/status"
          curl -sf -u "$SONAR_TOKEN:" "$BASE/api/system/status" && echo

      # Single scan step, nothing else
      - name: Sonar scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: |
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.log.level=DEBUG
            -Dsonar.verbose=true
            -Dsonar.scanner.http.connectTimeout=60000
            -Dsonar.scanner.http.socketTimeout=600000
